"""This notebook demonstrates how to load and explore data for ML projects."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_data.ipynb.

# %% auto #0
__all__ = ['data', 'df', 'missing_values', 'target_counts', 'X', 'y', 'X_train', 'X_test', 'y_train', 'y_test', 'scaler',
           'X_train_scaled', 'X_test_scaled']

# %% ../../nbs/02_data.ipynb #a454258d
import pandas as pd
import numpy as np


# %% ../../nbs/02_data.ipynb #c49f6a69
# Create sample data
data = {
    'feature_1': np.random.randn(100),
    'feature_2': np.random.randn(100) * 2 + 1,
    'feature_3': np.random.randn(100) * 0.5,
    'target': (np.random.randn(100) > 0).astype(int)
}
df = pd.DataFrame(data)

print(f"Dataset shape: {df.shape}")
print(df.head())


# %% ../../nbs/02_data.ipynb #1518ab65
df.describe()

# %% ../../nbs/02_data.ipynb #78300fe4
missing_values = df.isnull().sum()
print("Missing values per column:")
print(missing_values)
print(f"Total missing values: {missing_values.sum()}")


# %% ../../nbs/02_data.ipynb #1964e2dc
target_counts = df['target'].value_counts()
print("Target distribution:")
print(target_counts)
print(f"\nClass balance: {target_counts[0]/len(df):.2%} negative, {target_counts[1]/len(df):.2%} positive")


# %% ../../nbs/02_data.ipynb #9d017e41
# Separate features and target
X = df.drop('target', axis=1)
y = df['target']

# Split into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training set size: " + str(X_train.shape))
print("Test set size: " + str(X_test.shape))


# %% ../../nbs/02_data.ipynb #def8b97d
# Initialize scaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit on training data and transform both train and test
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Convert back to DataFrame for convenience
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X.columns, index=X_train.index)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X.columns, index=X_test.index)

print("Feature scaling completed.")
print(f"Training data mean: {X_train_scaled.mean().mean():.2f}, std: {X_train_scaled.std().mean():.2f}")

