{ ... }:

let
  dockerfile = ''
    # AUTOGENERATED from nix/terranix/docker-artifacts.nix
    FROM python:3.13-slim

    ENV PYTHONDONTWRITEBYTECODE=1 \
        PYTHONUNBUFFERED=1 \
        UV_LINK_MODE=copy \
        PATH="/root/.local/bin:''${PATH}"

    RUN apt-get update \
        && apt-get install -y --no-install-recommends build-essential curl git \
        && rm -rf /var/lib/apt/lists/*

    RUN curl -LsSf https://astral.sh/uv/install.sh | sh

    WORKDIR /workspace

    COPY pyproject.toml README.md /workspace/
    COPY uv.lock /workspace/uv.lock
    RUN uv sync --frozen

    CMD ["bash"]
  '';

  # OpenTofu JSON configuration for local emulation profile
  opentofuLocal = {
    terraform = {
      required_version = ">= 1.0";
      required_providers = {
        docker = {
          source = "kreuzwerker/docker";
          version = "~> 3.0";
        };
      };
    };

    provider.docker = {
      host = "unix:///var/run/docker.sock";
    };

    resource.docker_network.ml_local = {
      name = "ml_local";
      driver = "bridge";
    };

    resource.docker_container.traefik = {
      name = "ml_deploy_traefik";
      image = "traefik:v3.1.1";
      ports = [
        { internal = 80; external = 80; }
        { internal = 443; external = 443; }
        { internal = 8080; external = 8080; }
      ];
      volumes = [
        { host_path = "/var/run/docker.sock"; container_path = "/var/run/docker.sock"; }
      ];
      networks_advanced = [
        { name = "ml_local"; }
      ];
      command = [
        "--api.insecure=true"
        "--api.dashboard=true"
        "--entrypoints.web.address=:80"
        "--entrypoints.websecure.address=:443"
        "--providers.docker=true"
        "--providers.docker.exposedbydefault=false"
        "--providers.docker.network=ml_local"
      ];
      depends_on = [ "docker_network.ml_local" ];
    };

    resource.docker_container.postgres = {
      name = "ml_deploy_postgres";
      image = "postgres:16-alpine";
      env = [
        "POSTGRES_USER=mlflow"
        "POSTGRES_PASSWORD=mlflow"
        "POSTGRES_DB=mlflow"
      ];
      ports = [
        { internal = 5432; external = 5432; }
      ];
      networks_advanced = [
        { name = "ml_local"; }
      ];
      healthcheck = {
        test = [ "CMD-SHELL" "pg_isready -U mlflow" ];
        interval = "5s";
        timeout = "3s";
        retries = 20;
      };
      depends_on = [ "docker_network.ml_local" ];
    };

    resource.docker_container.mlflow = {
      name = "ml_deploy_mlflow";
      image = "ghcr.io/mlflow/mlflow:v2.14.2";
      env = [
        "AWS_ACCESS_KEY_ID=test"
        "AWS_SECRET_ACCESS_KEY=test"
        "AWS_DEFAULT_REGION=us-east-1"
        "MLFLOW_S3_ENDPOINT_URL=http://floci:4566"
      ];
      ports = [
        { internal = 5000; external = 5000; }
      ];
      networks_advanced = [
        { name = "ml_local"; }
      ];
      command = [
        "mlflow" "server" "--host" "0.0.0.0" "--port" "5000"
        "--backend-store-uri" "postgresql://mlflow:mlflow@postgres:5432/mlflow"
        "--artifacts-destination" "s3://mlflow"
      ];
      labels = {
        "traefik.enable" = "true";
        "traefik.http.routers.mlflow.rule" = "Host(`mlflow.local`)";
        "traefik.http.routers.mlflow.entrypoints" = "web";
        "traefik.http.services.mlflow.loadbalancer.server.port" = "5000";
      };
      depends_on = [
        "docker_container.postgres"
        "docker_network.ml_local"
      ];
    };

    output.local_infra_id = {
      value = "docker_network.ml_local.id";
      description = "Local infrastructure network ID";
    };
  };

  # OpenTofu JSON configuration for cloud deployment profile
  opentofuCloud = {
    terraform = {
      required_version = ">= 1.0";
      required_providers = {
        aws = {
          source = "hashicorp/aws";
          version = "~> 5.0";
        };
        kubernetes = {
          source = "hashicorp/kubernetes";
          version = "~> 2.0";
        };
      };
    };

    provider = {
      aws = {
        region = "us-east-1";
      };
      kubernetes = {
        host = "\${aws_eks_cluster.ml_deploy.endpoint}";
        cluster_ca_certificate = "\${base64decode(aws_eks_cluster.ml_deploy.certificate_authority[0].data)}";
        token = "\${data.aws_eks_cluster_auth.ml_deploy.token}";
      };
    };

    data.aws_eks_cluster_auth.ml_deploy = {
      name = "\${aws_eks_cluster.ml_deploy.name}";
    };

    resource = {
      aws_eks_cluster.ml_deploy = {
        name = "ml-deploy-cluster";
        role_arn = "\${aws_iam_role.eks_cluster_role.arn}";
        vpc_config = {
          subnet_ids = [ "\${aws_subnet.ml_deploy.id}" ];
        };
      };

      aws_iam_role.eks_cluster_role = {
        name = "ml-deploy-eks-cluster-role";
        assume_role_policy = builtins.toJSON {
          Version = "2012-10-17";
          Statement = [
            {
              Action = "sts:AssumeRole";
              Effect = "Allow";
              Principal = {
                Service = "eks.amazonaws.com";
              };
            }
          ];
        };
      };

      aws_vpc.ml_deploy = {
        cidr_block = "10.0.0.0/16";
        enable_dns_hostnames = true;
      };

      aws_subnet.ml_deploy = {
        vpc_id = "\${aws_vpc.ml_deploy.id}";
        cidr_block = "10.0.1.0/24";
      };

      aws_s3_bucket.mlflow_artifacts = {
        bucket = "ml-deploy-mlflow-artifacts";
        tags = {
          Name = "MLflow Artifacts";
          Environment = "production";
        };
      };

      aws_rds_cluster.mlflow = {
        cluster_identifier = "ml-deploy-mlflow";
        engine = "aurora-postgresql";
        database_name = "mlflow";
        master_username = "mlflow";
        master_password = "\${random_password.mlflow_db_password.result}";
        skip_final_snapshot = false;
      };
    };

    random_password.mlflow_db_password = {
      length = 16;
      special = true;
    };

    output = {
      eks_cluster_name = {
        value = "\${aws_eks_cluster.ml_deploy.name}";
        description = "EKS cluster name";
      };
      s3_bucket_name = {
        value = "\${aws_s3_bucket.mlflow_artifacts.bucket}";
        description = "S3 bucket for MLflow artifacts";
      };
      rds_cluster_endpoint = {
        value = "\${aws_rds_cluster.mlflow.endpoint}";
        description = "RDS cluster endpoint";
      };
    };
  };
in
{
  artifacts = {
    dockerfile = dockerfile;

    composeDev = {
      services = {
        traefik = {
          image = "traefik:v3.1.1";
          ports = [ "80:80" "443:443" "8080:8080" ];
          volumes = [ "/var/run/docker.sock:/var/run/docker.sock" ];
          networks = [ "ml_local" ];
          command = [
            "--api.insecure=true"
            "--api.dashboard=true"
            "--entrypoints.web.address=:80"
            "--entrypoints.websecure.address=:443"
            "--providers.docker=true"
            "--providers.docker.exposedbydefault=false"
            "--providers.docker.network=ml_local"
          ];
        };

        dev = {
          build = { context = "."; dockerfile = "Dockerfile"; };
          working_dir = "/workspace";
          command = "bash -lc \"uv sync --frozen && bash\"";
          volumes = [ "./:/workspace" ];
          networks = [ "ml_local" ];
          environment = {
            MLFLOW_TRACKING_URI = "http://traefik/mlflow";
            MLFLOW_BACKEND_STORE_URI = "postgresql://mlflow:mlflow@postgres:5432/mlflow";
            MLFLOW_ARTIFACTS_DESTINATION = "s3://mlflow";
            AWS_ACCESS_KEY_ID = "test";
            AWS_SECRET_ACCESS_KEY = "test";
            AWS_DEFAULT_REGION = "us-east-1";
            MLFLOW_S3_ENDPOINT_URL = "http://floci:4566";
          };
          depends_on = {
            traefik = { condition = "service_started"; };
            postgres = { condition = "service_healthy"; };
            mlflow = { condition = "service_started"; };
          };
          stdin_open = true;
          tty = true;
        };

        postgres = {
          image = "postgres:16-alpine";
          environment = {
            POSTGRES_USER = "mlflow";
            POSTGRES_PASSWORD = "mlflow";
            POSTGRES_DB = "mlflow";
          };
          ports = [ "5432:5432" ];
          networks = [ "ml_local" ];
          healthcheck = {
            test = [ "CMD-SHELL" "pg_isready -U $${POSTGRES_USER}" ];
            interval = "5s";
            timeout = "3s";
            retries = 20;
          };
        };

        mlflow = {
          image = "ghcr.io/mlflow/mlflow:v2.14.2";
          depends_on = { postgres = { condition = "service_healthy"; }; };
          networks = [ "ml_local" ];
          command = [
            "mlflow" "server" "--host" "0.0.0.0" "--port" "5000"
            "--backend-store-uri" "postgresql://mlflow:mlflow@postgres:5432/mlflow"
            "--artifacts-destination" "s3://mlflow"
          ];
          environment = {
            AWS_ACCESS_KEY_ID = "test";
            AWS_SECRET_ACCESS_KEY = "test";
            AWS_DEFAULT_REGION = "us-east-1";
            MLFLOW_S3_ENDPOINT_URL = "http://floci:4566";
          };
          labels = {
            "traefik.enable" = "true";
            "traefik.http.routers.mlflow.rule" = "PathPrefix(`/mlflow`)";
            "traefik.http.routers.mlflow.service" = "mlflow-service";
            "traefik.http.services.mlflow-service.loadbalancer.server.port" = "5000";
          };
        };
      };
      networks.ml_local = { name = "ml_local"; driver = "bridge"; };
    };

    composeAwsEmulator = {
      services = {
        floci = {
          image = "floci/floci:latest";
          container_name = "ml_deploy_floci";
          user = "root";
          networks = [ "ml_local" ];
          ports = [ "4566:4566" ];
          environment = {
            FLOCI_HOSTNAME = "floci";
            FLOCI_STORAGE_MODE = "persistent";
            AWS_DEFAULT_REGION = "us-east-1";
          };
          volumes = [
            "/var/run/docker.sock:/var/run/docker.sock"
            "floci_data:/var/lib/floci"
          ];
          healthcheck = {
            test = [ "CMD" "curl" "-f" "http://localhost:4566/_localstack/health" ];
            interval = "15s";
            timeout = "10s";
            retries = 5;
            start_period = "20s";
          };
        };

        floci_bootstrap = {
          image = "amazon/aws-cli:2.15.56";
          container_name = "ml_deploy_floci_bootstrap";
          depends_on = { floci = { condition = "service_healthy"; }; };
          networks = [ "ml_local" ];
          environment = {
            AWS_ACCESS_KEY_ID = "test";
            AWS_SECRET_ACCESS_KEY = "test";
            AWS_DEFAULT_REGION = "us-east-1";
            AWS_ENDPOINT_URL = "http://floci:4566";
          };
          entrypoint = [ "/bin/sh" "-c" ];
          command = [
            ''
              echo "Initialising Floci buckets and roles..."
              aws s3 mb s3://mlflow-artifacts --endpoint-url=http://floci:4566 || true
              aws s3 mb s3://model-registry --endpoint-url=http://floci:4566 || true
              aws iam create-role \
                --role-name ml-deploy-local \
                --assume-role-policy-document '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"ec2.amazonaws.com"},"Action":"sts:AssumeRole"}]}' \
                --endpoint-url=http://floci:4566 || true
              echo "Floci init complete."
            ''
          ];
        };
      };
      volumes.floci_data = { };
      networks.ml_local = { name = "ml_local"; driver = "bridge"; };
    };

    composeCloud = {
      services = {
        traefik = {
          image = "traefik:v3.1.1";
          ports = [ "80:80" "443:443" ];
          volumes = [ "/var/run/docker.sock:/var/run/docker.sock" ];
          networks = [ "ml_cloud" ];
          command = [
            "--entrypoints.web.address=:80"
            "--entrypoints.websecure.address=:443"
            "--providers.docker=true"
            "--providers.docker.exposedbydefault=false"
            "--providers.docker.network=ml_cloud"
          ];
        };

        mlflow = {
          image = "ghcr.io/mlflow/mlflow:v2.14.2";
          networks = [ "ml_cloud" ];
          environment = {
            MLFLOW_BACKEND_STORE_URI = "postgresql://mlflow:mlflow@postgres:5432/mlflow";
            MLFLOW_ARTIFACTS_DESTINATION = "s3://mlflow-artifacts";
            MLFLOW_CREATE_MODEL_VERSION_SOURCE_VALIDATION_REGEX = "^s3://mlflow-artifacts/.*";
          };
          labels = {
            "traefik.enable" = "true";
            "traefik.http.routers.mlflow.rule" = "Host(`mlflow.internal`)";
            "traefik.http.routers.mlflow.entrypoints" = "websecure";
            "traefik.http.services.mlflow.loadbalancer.server.port" = "5000";
          };
        };
      };
      networks.ml_cloud = { name = "ml_cloud"; driver = "bridge"; };
    };

    opentofuJsonLocal = opentofuLocal;
    opentofuJsonCloud = opentofuCloud;
  };
}
