#!/usr/bin/env bash
/usr/bin/env jupyter-lab --no-browser \
                         --ip="*" \
                         --NotebookApp.token= \
                         --NotebookApp.password= \
                         --ServerApp.disable_check_xsrf=True
