"""Checks for generated Docker artifacts and cloud Traefik/MLflow wiring."""

from __future__ import annotations

from pathlib import Path
import unittest


class TestDockerArtifactsGeneration(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.repo_root = Path(__file__).resolve().parents[1]

    def test_dockerfile_is_generated(self) -> None:
        dockerfile = (self.repo_root / "Dockerfile").read_text(encoding="utf-8")
        self.assertIn("# AUTOGENERATED from nix/terranix/docker-artifacts.nix", dockerfile)

    def test_compose_dev_is_generated(self) -> None:
        compose_dev = (self.repo_root / "docker-compose.dev.yml").read_text(encoding="utf-8")
        self.assertIn("# AUTOGENERATED from nix/terranix/docker-artifacts.nix", compose_dev)

    def test_cloud_profile_contains_traefik_and_source_validation(self) -> None:
        compose_cloud = (self.repo_root / "docker-compose.cloud.yml").read_text(
            encoding="utf-8"
        )
        self.assertIn("traefik", compose_cloud)
        self.assertIn("MLFLOW_CREATE_MODEL_VERSION_SOURCE_VALIDATION_REGEX", compose_cloud)


if __name__ == "__main__":
    unittest.main()
