#!/usr/bin/env python3
"""Generate Docker artifacts and OpenTofu configurations from Nix Terranix source-of-truth."""

from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
NIX_ARTIFACTS_FILE = REPO_ROOT / "nix" / "terranix" / "docker-artifacts.nix"
TF_OUTPUT_DIR = REPO_ROOT / "terraform" / "generated"


def _run_nix_eval() -> dict[str, Any]:
    expression = "let p = import " + json.dumps(str(NIX_ARTIFACTS_FILE)) + " {}; in p.artifacts"
    command = [
        "nix",
        "eval",
        "--impure",
        "--json",
        "--expr",
        expression,
    ]
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "nix eval failed")
    return json.loads(result.stdout)


def _dump_json_yaml(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(
        "# AUTOGENERATED from nix/terranix/docker-artifacts.nix\n"
        + json.dumps(payload, indent=2)
        + "\n",
        encoding="utf-8",
    )


def _dump_opentofu_json(path: Path, payload: dict[str, Any]) -> None:
    """Dump OpenTofu JSON configuration with header."""
    path.write_text(
        json.dumps(payload, indent=2)
        + "\n",
        encoding="utf-8",
    )


def main() -> int:
    artifacts = _run_nix_eval()

    dockerfile = artifacts["dockerfile"]
    (REPO_ROOT / "Dockerfile").write_text(dockerfile + "\n", encoding="utf-8")
    _dump_json_yaml(REPO_ROOT / "docker-compose.dev.yml", artifacts["composeDev"])
    _dump_json_yaml(
        REPO_ROOT / "docker-compose.aws-emulator.yml", artifacts["composeAwsEmulator"]
    )
    _dump_json_yaml(REPO_ROOT / "docker-compose.cloud.yml", artifacts["composeCloud"])
    
    # Generate OpenTofu JSON configurations
    tf_output_dir = TF_OUTPUT_DIR
    tf_output_dir.mkdir(parents=True, exist_ok=True)
    
    if "opentofuJsonLocal" in artifacts:
        _dump_opentofu_json(
            tf_output_dir / "local.tf.json",
            artifacts["opentofuJsonLocal"]
        )
    
    if "opentofuJsonCloud" in artifacts:
        _dump_opentofu_json(
            tf_output_dir / "cloud.tf.json",
            artifacts["opentofuJsonCloud"]
        )
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
