# Autogenerated by nbdev

d = { 'settings': {'branch': 'main', 'doc_baseurl': '/', 'doc_host': '', 'git_url': '', 'lib_path': 'ml_deploy'},
  'syms': { 'ml_deploy.ml_deploy': { 'ml_deploy.ml_deploy.add_numbers': ('core.html#add_numbers', 'ml_deploy/ml_deploy.py'),
                                     'ml_deploy.ml_deploy.say_hello': ('core.html#say_hello', 'ml_deploy/ml_deploy.py')},
            'ml_deploy.ml_deploy.data': {},
            'ml_deploy.ml_deploy.training': {}}}
