"""A Python package for ML deployment reference."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['say_hello', 'add_numbers']

# %% ../nbs/00_core.ipynb #fd762af7
"""Top-level package for ml_deploy."""

__author__ = """ML Engineer"""
__email__ = 'ml@example.com'
__version__ = '0.1.0'


def say_hello() -> str:
    """Return a greeting message."""
    return "Hello from ml_deploy!"


def add_numbers(a: int, b: int) -> int:
    """Add two numbers and return the result."""
    return a + b

